###############################
# RHEL/CentOS based Systems   #
###############################
---
- name: Install device-mapper-persistent-data, lmv2, yum utiles
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - yum-utils
   - device-mapper-persistent-data
   - lvm2
  when: ansible_os_family == 'RedHat'

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Install Docker
  yum:
    name: docker
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure Kubernetes repository exists.
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    baseurl: "{{ kubernetes_yum_base_url }}"
    gpgkey: "{{ kubernetes_yum_gpg_key }}"

- name: Add Kubernetes GPG keys.
  rpm_key:
    key: "{{ item }}"
    state: present
  register: kubernetes_rpm_key
  with_items: "{{ kubernetes_yum_gpg_key }}"

- name: Make cache if Kubernetes GPG key changed.
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
  when: kubernetes_rpm_key is changed
  args:
    warn: false

- name: copy daemon.json file
  files:
    src: daemon.json
    dest: /etc/docker/
    owner: root
    group: root
    chmod: 0644
  notify: daemon_reload
