---
kubernetes_packages:
  - name: kubelet
    state: present
  - name: kubectl
    state: present
  - name: kubeadm
    state: present
  - name: kubernetes-cni
    state: present


kubernetes_version: '1.21.1'
etcd_version: 'v3.4.16'
kubernetes_version_rhel_package: '1.21.1'
apiPort: "6443"
domainName: "maranet.tk"
master_address: "{{ hostvars[groups['masters'][0]].ansible_host }}"

kubernetes_role: master

# This is deprecated. Please use kubernetes_config_kubelet_configuration instead.
kubernetes_kubelet_extra_args: ""

kubernetes_kubeadm_init_extra_opts: ""
kubernetes_join_command_extra_opts: ""
kubernetes_allow_pods_on_master: false
kubernetes_enable_web_ui: false
kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml
kubernetes_pod_network:
  # Flannel CNI.
  #cni: 'flannel'
  #podRange: '10.244.0.0/16'
  #svcRange: '10.96.0.0/12'
  # Calico CNI.
  cni: 'calico'
  podRange: '192.168.0.0/16'
  svcRange: '10.96.0.0/12'

kubernetes_kubeadm_kubelet_config_file_path: '/etc/kubernetes/kubeadm-kubelet-config.yaml'
kubernetes_config_kubelet_configuration:
  cgroupDriver: "systemd"

# <<<<<<<<<<<<<<<<<<<<<<<<< New
kubernetes_config_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
  nodeRegistration:
    criSocket: /var/run/dockershim.sock
    name: "{{ hostvars[groups['masters'][0]].node_name }}"
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  
# <<<<<<<<<<<<<<<<<<<<<<<<< New
kubeadm_apiServer_configuration:
  apiServer:
    extraArgs:
      authorization-mode: "Node,RBAC"
    timeoutForControlPlane: 4m0s
    certSANs:
    - "{{ hostvars[groups['masters'][0]].ansible_host }}"
    - "{{ hostvars[groups['masters'][0]].node_name }}"
    - "{{ hostvars[groups['masters'][0]].node_name }}.{{ domainName }}"

certificates_directory: /etc/kubernetes/pki
cluster_name: kubernetes
controller_manager: {}
kubeImageRepository: "k8s.gcr.io"

# <<<<<<<<<<<<<<<<<<<<<<<<< New
kubeadm_config_token_configuration:
  bootstrapTokens:
  - groups:
    - system:bootstrappers:kubeadm:default-node-token
    token: 123456.3123fe2e098799f3
    ttl: 24h0m0s
    usages:
    - signing
    - authentication
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
kubernetes_config_cluster_configuration:
  networking:
    serviceSubnet: "{{ kubernetes_pod_network.svcRange }}"
    podSubnet: "{{ kubernetes_pod_network.podRange }}"

kubeadm_dns_configuration:
  dns:
    type: CoreDNS

kubeadm_etcd_configuration:
  etcd:
    local:
      imageRepository: "quay.io/coreos"
      imageTag: "{{etcd_version}}"
      dataDir: "/var/lib/etcd"
      serverCertSANs:
        - "{{ hostvars[groups['masters'][0]].ansible_host }}"
        - "{{ hostvars[groups['masters'][0]].node_name }}"
        - "{{ hostvars[groups['masters'][0]].node_name }}.{{ domainName }}"
      peerCertSANs:
        - "{{ hostvars[groups['masters'][0]].ansible_host }}"
        - "{{ hostvars[groups['masters'][0]].node_name }}"
        - "{{ hostvars[groups['masters'][0]].node_name }}.{{ domainName }}"
# --------------------------------------------
kubernetes_apiserver_advertise_address: "{{ hostvars[groups['masters'][0]].ansible_host }}"
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'
kubernetes_ignore_preflight_errors: 'all'

kubernetes_apt_release_channel: main
# Note that xenial repo is used for all Debian derivatives at this time.
kubernetes_apt_repository: "deb http://apt.kubernetes.io/ kubernetes-xenial {{ kubernetes_apt_release_channel }}"
kubernetes_apt_ignore_key_error: false

kubernetes_yum_arch: '$basearch'
kubernetes_yum_base_url: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ kubernetes_yum_arch }}"
kubernetes_yum_gpg_key:
  - https://packages.cloud.google.com/yum/doc/yum-key.gpg
  - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

# Flannel config files.
kubernetes_flannel_manifest_file_rbac: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
kubernetes_flannel_manifest_file: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# Calico config files
kubernetes_calico_manifest_file: https://docs.projectcalico.org/v3.19/manifests/calico.yaml
