---
- name: daemon reload
  systemd:
    daemon_reload: yes
    state: restarted
  become: true


- name: restart kubelet
  service:
     name: kubelet
     state: restarted
     enabled: started

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
